# -*- coding: utf-8 -*-
"""clustering-percent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRy61Z9gCFG03nitaMOkDRTFsXjQN2RJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

from sklearn.cluster import KMeans


from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.decomposition import PCA
from yellowbrick.cluster import KElbowVisualizer

df = pd.read_csv("IKP_percent_only.csv")

df

df = df.rename(columns={
    "I.1.1.1": "Rasio Gini Tanah",
    "I.2.1.1": "Luas Tanah yang Dikuasai",
    "I.3.1.1": "Ketersediaan Air untuk Budidaya",
    "I.4.1.1": "Asal Benih",
    "II.1.1.2": "Pengadaan Pestisida",
    "II.1.2.3": "Pengadaan Pupuk",
    "II.1.3.1": "Melakukan pemanfaatan limbah pertanian",
    "II.2.2.1": "Keragaman Jenis Tanaman",
    "II.3.3.1": "Nilai Tukar Petani",
    "II.3.3.2": "Rasio rerata penghasilan dengan UMK",
    "III.1.1.1": "Pola Pangan Harapan (PPH)",
    "III.1.1.2": "Indeks Shanon Weiner",
    "III.1.2.1": "Asal Bahan Baku",
    "III.1.4.1": "Daya dukung pangan"
})

df.isna().sum()

df["Melakukan pemanfaatan limbah pertanian"] = df["Melakukan pemanfaatan limbah pertanian"].fillna(0)

df.info()

df

"""### analisis distribusi"""

#memisahkan data numerik dan kategorik
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

df[numerical_cols].describe().T

cols = 3
rows = math.ceil(len(numerical_cols) / cols)

fig, axes = plt.subplots(rows, cols, figsize=(15, rows * 4))
axes = axes.flatten()

for i, col in enumerate(numerical_cols):
    sns.histplot(df[col], kde=True, bins=30, ax=axes[i])
    axes[i].set_title(f"Distribution of {col}")

# hapus subplot kosong
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout(pad=3)
plt.show()

fig, axes = plt.subplots(rows, cols, figsize=(15, rows*4))
axes = axes.flatten()

for i, col in enumerate(numerical_cols):
    sns.boxplot(x=df[col], ax=axes[i])
    axes[i].set_title(f'Boxplot of {col}')
    axes[i].set_xlabel(col)

# hapus subplot kosong (kalau ada)
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout(pad=3)
plt.show()

plt.figure(figsize=(10,8))
correlation_matrix = df[numerical_cols].corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Matrix')
plt.show()

scaler = MinMaxScaler()
df_normalized = df.copy()
df_normalized[numerical_cols] = scaler.fit_transform(df[numerical_cols])

for i, column in enumerate(numerical_cols, 1):
    plt.subplot(rows, cols, i)
    sns.histplot(df_normalized[column], kde=True, bins=30)
    plt.title(f'Distribution of {column}')

plt.tight_layout()
plt.show()

df_normalized

df_normalized.info()

df_normalized_num = df_normalized.select_dtypes(include=['number'])

df_normalized_num

df_normalized_num = df_normalized.copy()

df_normalized_num = df_normalized_num.drop("Desa/Kelurahan", axis=1)

df_normalized_num

df_normalized_num.info()

"""### pembangunan model clustering"""

silhouette_scores = []
for i in range(2, 10):
    kmeans = KMeans(
        n_clusters=i,
        init='k-means++',
        random_state=42
    )
    kmeans.fit(df_normalized_num)
    silhouette_scores.append(silhouette_score(df_normalized_num, kmeans.labels_))

plt.plot(range(2,10), silhouette_scores, marker='o')
plt.title('Silhouette Score')
plt.xlabel('Number of Clusters')
plt.ylabel('Silhouette Score')
plt.show

# melatih model

model_kmeans = KMeans (
    n_clusters=4,
    init='k-means++',
    random_state=42
)
model_kmeans.fit(df_normalized_num)
silhouette_score(df_normalized_num, model_kmeans.labels_)

"""### visualisasi hasil clustering"""

pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_normalized_num)

plt.figure(figsize=(8,5))
sns.scatterplot(x=df_pca[:, 0], y=df_pca[:, 1], hue=model_kmeans.labels_, palette='viridis', alpha=0.7)
plt.title('KMeans Clustering')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

df_normalized_num['cluster'] = model_kmeans.labels_

df_normalized['cluster'] = df_normalized_num['cluster']

df_normalized

# variabel numerik

plt.figure(figsize=(15,25))
for i, column in enumerate(numerical_cols, 1):
    plt.subplot(rows, cols, i)
    sns.boxplot(x='cluster', y=column, data=df_normalized)
    plt.title(f'Distribution of {column} by Cluster')

plt.tight_layout()
plt.show()

"""## coba hierarchical clustering"""

from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

# Simpan nama desa terpisah
desa = df["Desa/Kelurahan"]

# Ambil hanya variabel numerik
X = df.drop("Desa/Kelurahan", axis=1)

# Tangani missing value (misalnya isi dengan median)
X = X.fillna(X.median())

# (opsional) Scaling → lebih adil antar indikator
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# linkage: 'ward' cocok untuk data numerik
Z = linkage(X_scaled, method='ward')

plt.figure(figsize=(12,6))
dendrogram(Z, labels=desa.values, leaf_rotation=90)
plt.title("Hierarchical Clustering Dendrogram (Ward Linkage)")
plt.xlabel("Desa")
plt.ylabel("Distance")
plt.tight_layout()
plt.show()

clusters = fcluster(Z, 4, criterion="maxclust")

df_clusters = pd.DataFrame({
    "Desa": desa,
    "Cluster": clusters
})

print(df_clusters.sort_values("Cluster"))

df_hc = df.copy()

df_hc['cluster'] = df_clusters['Cluster']

df_hc

plt.figure(figsize=(15, 25))
for i, column in enumerate(numerical_cols, 1):
    plt.subplot(rows, cols, i)
    sns.boxplot(x="cluster", y=column, data=df_hc)
    plt.title(f"Distribution of {column} by Cluster")

plt.tight_layout()
plt.show()

# Palet warna terang / pastel
palette=palette

fig, axes = plt.subplots(rows, cols, figsize=(15, rows * 4))
axes = axes.flatten()

for i, col in enumerate(numerical_cols):
    sns.histplot(
        data=df,
        x=col,
        hue="Cluster",
        bins=30,
        multiple="layer",
        stat="count",
        common_bins=True,
        alpha=0.6,         # transparansi lebih tinggi
        palette=palette,
        ax=axes[i]
    )

    sns.kdeplot(
        data=df,
        x=col,
        hue="Cluster",
        common_norm=False,
        linewidth=1.3,
        legend=False,
        palette=palette,
        ax=axes[i]
    )

    axes[i].set_title(f"Distribution of {col}", fontsize=12, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel("Count")

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout(pad=3)
plt.show()



